#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum class WINMODE { FULL, WIN, END };	
	enum class PROTOTYPE { GAMEOBJECT, COMPONENT };
	enum class WORLDSTATE { RIGHT, UP, LOOK, POSITION, END };

	enum class RENDER { PRIORITY,
						NONBLEND, ALPHATEST,
						BLEND, PARTICLE,
						PROJECTION_UI, ORTTHO_UI, BLENDUI, END};

	enum class TEXTURE { PLANE, CUBE, END };
	enum class RAY { VIEW, WORLD, END };
	enum class COLLISION_TYPE { BOX, SPHERE, END };
	enum class LIGHT_TYPE{ POINT = 1, SPOT, DIRECATION, END};
	enum CHANNELID { SOUND_EFFECT, SOUND_EFFECT2, SOUND_EFFECT3, SOUND_EFFECT4, BADMONSTER_SOUND, GOODMONSTER_SOUND, PLAYER_SOUND, SOUND_BGM, SOUND_ITEM, SOUND_UI, SOUND_END };
}
#endif // Engine_Enum_h__
